### ISSUE TITLE
Add an athlete

### ISSUE THREAD

**Issue by johnnymetz** [johnnymetz/famous-athletes#1]
- Add an athlete to the `athletes` folder as a json file
- Include the athlete's `name`, `height` and `date_of_birth`
- Name the json file as a concatenation of the athlete's name (e.g. First Last = `first_last.json`)

**Comment by GSantos23** [comment]
What do you need to do?

**Comment by johnnymetz** [comment]
@GSantos23 just updated the description above!

**Comment by salilbc** [comment]
added a couple of runners PR https://github.com/johnnymetz/famous-athletes/pull/10
