### ISSUE TITLE
Can I change the height of the athletes?

### ISSUE THREAD

**Issue by BrantLauro** [johnnymetz/famous-athletes#62]
I was seeing you repository and I found something a little strange, the height was in ft, I don't understand this well, because it cant be float then they put "79", I thinks this is "7.9" and its kind of tall, bizarre. Antetokounmpo with 83, that is to much, so If you can fix it or change it to cm, all right, but if you can't, I can do it for you, just let me know! Thanks for you attention

**Comment by johnnymetz** [comment]
Thanks for reaching out! The height should be an integer in inches. That's the standard in the United States. We can covert it to anything we want as a property in the `Athlete` dataclass. For example, we convert the height to feet [here](https://github.com/johnnymetz/famous-athletes/blob/master/models.py#L12).

**Comment by BrantLauro** [comment]
Oh, Inches! All Right, so I will change my athletes to Inches in some minutes, thank you for your attention!
